# Build settings
theme: null # This prevents github-pages gem from forcing a theme which outputs a default stylesheet that we don't need.

plugins:
  - jekyll-feed
  - jemoji
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - Makefile

# Site settings
permalink: pretty
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      title: "" # Explicitly add a title if you want a non-micro post.
      excerpt_separator: <!-- more -->
  - scope:
      path: ""
    values:
      layout: "default"

# Site variables
title: The Upshift
description: The words & work of Gamba SK

# emojis

