# Build settings
theme: null # This prevents github-pages gem from forcing a theme which outputs a default stylesheet that we don't need.

plugins:
  - jekyll-feed
  - jemoji
  - disqus-for-jekyll

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - Makefile

# Site settings
permalink: pretty
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      title: "" # Explicitly add a title if you want a non-micro post.
      excerpt_separator: <!-- more -->
  - scope:
      path: ""
    values:
      layout: "default"

# Site variables
title: The Upshift
description: The words & work of Gamba SK

# Disqus Comments

disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: upshift-tk.disqus.com
