comments:
  endpoint: https://api.staticman.net/v2/entry/github/theupshift/theupshift.github.io/master/comments
  allowedFields: [name, email, message]
  branch: master
  moderation: true   # new comments require PR approval
